serial :
	gcc serial.c -Wall -o tema1serial
paralel :
	gcc paralel.c -Wall -fopenmp -o tema1paralel
clean :
	rm -rf tema1paralel
	rm -rf tema1serial
all :	
	gcc serial.c -Wall -o tema1serial
	gcc paralel.c -Wall -fopenmp -o tema1paralel
	
